### ISSUE TITLE
Use UTC time

### ISSUE THREAD

**Issue by Kappeh** [Kappeh/Redstone-Squid#11]
There a handful of instances where local times are used without time zone information, for example
```py
datetime.now().strftime(r'%Y-%m-%d %H:%M:%S.%f')
```
Times within the database should be stored in UTC. As such, these should be updated to use UTC, such as
```py
datetime.utcnow().strftime(r'%Y-%m-%d %H:%M:%S.%f') // Edit: NOT THIS ONE
```
or
```py
datetime.now(timezone.utc).strftime(r'%Y-%m-%d %H:%M:%S.%f')
```

**Comment by Glinte** [comment]
![image](https://github.com/Kappeh/Redstone-Squid/assets/96855131/6ba742b8-7717-4bcb-859f-e05744ed1cf2)

**Comment by Glinte** [comment]
Also fix the database inconsistency (perhaps by nuking all previous rows except id=30)
